- dockerfile-mode.el
Emacs provides `mode-require-final-newline` to allow users to control the behaviour of modes (like `dockerfile-mode`) which are designed to control the final newline in a file. The intent is that this is set to
`t` by default - modes that wish to ensure a final newline should set `require-final-newline` to `mode-require-final-newline`, allowing users to override this behaviour. More detail can be found [here](http://www.gnu.org/software/emacs/manual/html_node/emacs/Customize-Save.html).
One specific use case where this is important is `ethan-wpace`, which implements a more sophisticated whitespace policy. Some examples of how sidestepping this convention can be a problem can be found in issues glasserc/ethan-wspace#22 and glasserc/ethan-wspace#25.
> Correctly set require-final-newline

- dockerfile-mode.el
This is useful for bindings that binds to this directly.
I'm using this function in https://github.com/Silex/docker.el
> Add autoload marker for `dockerfile-build-buffer`

- dockerfile-mode.el
LABELs are used extensively in Red Hat Dockerfiles, give them some
colors.
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>
> dockerfile-mode.el: add LABEL to the list of known keywords

- dockerfile-mode.el
Docker 1.9 introduced the `ARG` command which can be used in combination with `docker build --build-arg`. 
See: https://github.com/docker/docker/blob/master/CHANGELOG.md#builder
> Add support for ARG command

- dockerfile-mode.el
Since the substitutions into the format call were not escaped, the shell
was interpreting paths with spaces in them as two arguments. Surrounding
said paths in spaces forces the shell to treat the literal spaces in the
path as part of the path instaead of a separator. Escaping spaces (" "
-> "\ ") would probably be a nicer solution, but the code is less
simple.
> Fix build failure when path of Dockerfile contains spaces.

- dockerfile-mode.el
When `dockerfile-use-sudo` was set to `nil`, the shell command for
building an image would start with a space, which had no effect on a
Linux system, but broke the ability to build on Windows. The error
message ("docker is not a docker command") seemed to indicate that a
space in front of a command causes it to double in some way, but I am
unable to duplicate a similar error in CMD, PowerShell, or Docker
Toolbox's Bash, with our without quotation marks around the command,
i.e. " docker".
Nevertheless, moving the space from the beginning of the base string to
the end of the piece inserted when `dockerfile-use-sudo` is non-`nil`
fixes the problem.
This fix does not address the problem of initializing the proper
environment variables. Emacs needs to inherit the settings suggested by …
> Fix inability to build images on Windows.

- dockerfile-mode.el
From Docker 1.9.0, added `STOPSIGNAL` Dockerfile instruction.
see: https://github.com/docker/docker/releases/tag/v1.9.0 and https://docs.docker.com/engine/reference/builder/#stopsignal
> add a STOPSIGNAL Dockerfile instruction to font lock keywords

- dockerfile-mode.el
Previously, = was treated as a symbol character. This prevented things
like highlight-symbol-mode and isearch-forward-symbol being able to
find variables defined with `ENV FOO=1`.
> Treat = as punctuation.

- dockerfile-mode.el
Make filenames like `Dockerfile.example` or `Dockerfile.build` also 
open with `dockerfile-mode` automatically.
> Recognize Dockerfile files with extension

- README.md
This tells emacs that setting the local variable `dockerfile-image-name` to any string is safe, and it need not confirm with you. Cribbed from [stack overflow](https://stackoverflow.com/a/19813210).
> README.md addition for safe-local-variable

- dockerfile-mode.el
With new multistage builds it's quite difficult to orient oneself in where one stage starts and another ends.  This adds a little bit of a visual overview
An additional feature might be to also fontify the part in the `--from=` flag.
> Add faces for image name and alias

- dockerfile-mode.el
The build stages can now be accessed with `imenu`.
> Add imenu support

- dockerfile-mode.el
This adds support for e.g. `indent-region` by adding a custom `indent-line-function`. The algorithm is very simple, indenting lines beginning with keywords to column zero and everything else by `tab-width`. I believe this should go towards resolving #16.
> Adds a dead simple indentation function

- dockerfile-mode.el
Fix #45 
Since we look at beginning of line we look for `font-lock-comment-delimiter-face` instead of `font-lock-comment-face`.
> Support indentation for comments

- README.md
- dockerfile-mode.el
Make it possible to use a different binary than the docker command in the PATH. With this it is also possible to use podman instead of docker.
> Make it possible to use a differnt binary than in the path

- dockerfile-mode.el
This removes the keybinding to the function `dockerfile-test-function` which isn't defined as far as I was able to tell.  I added sharp-quotes in front of other keybound functions to raise compiler warnings in case those functions don't exist (or change names) in the future.
> Remove keybinding to #'dockerfile-test-function

- dockerfile-mode.el
The dependency on `s.el` is for a single function call which can be trivially replaced with a call to a standard function.  As this is the only non-standard dependency, I think it is sensible to eliminate it.
> Remove dependency on s.el

- dockerfile-mode.el
According to HEAD NEWS, 'The 'when' argument of `make-obsolete` and related functions is mandatory'.
> fix define-obsolete-function-alias error in Emacs28

- README.md
Minor change... the README.md had an inconsistent variable name. I spent ~10 minutes googling and trying to figure out why `(put 'dockerfile-image-name 'safe-local-variable #'stringp)` wasn't working until realizing the variable name was not consistent with the example image name tag above. Maybe this PR will save someone else that time. 😃
> FIX: make emacs lisp variable name consistent in README.md

- dockerfile-mode.el
For supported versions of docker, the `dockerfile-use-buildkit` option will set `DOCKER_BUILDKIT=1` in the buildcommand when building the current buffer image.
Tested on emacs 28.0.50, docker 19.03.12-ce but really shouldn't interfere with anything.
> Added the option to use docker buildkit

- dockerfile-mode.el
`tab-width` is not the size of an indentation step.
> NOTE: This controls the display width of a TAB character, and not the size of an indentation step.
>
> see `describe-variable` `tab-width`
So, I add dockerfile-indent-offset and respect `standard-indent`.
> added: dockerfile-indent-offset closed #16

- dockerfile-mode.el
The old pattern would match the following filenames:
- `*Dockerfile`
- `*Dockerfile.*`
This is because the pattern does not start with a slash indicating the beginning
of the basename. Personally this led to a few false positives, like for example
`siren-dockerfile.el` that sets up and configures dockerfile-mode in my Emacs
configuration.
This change restricts the patterns to:
- `Dockerfile`
- `Dockerfile.*`
- `*.dockerfile`
I believe this is still wide enough to capture all common naming conventions for
Dockerfiles.
> fix: false positives caused by auto-mode-alist pattern

- dockerfile-mode.el
The invocation of define-derived-mode defines the hook.
> Remove unnecessary declaration of dockerfile-mode-hook

- dockerfile-mode.el
This was annoying me as my preferred style looks like this...
```dockerfile
RUN set -exo pipefail             && \
\
echo 'Install tools'          && \
apk add --update --no-cache \
gzip                      \
make                      \
tar                         && \
\
echo 'Install aws-cli'        && \
pip3 install --no-cache-dir \
awscli
``` 
...and every time I'd paste something it would get messed up badly. Now I can disable it with:
```elisp
(with-eval-after-load 'dockerfile-mode
(setq dockerfile-enable-auto-indent nil))
```
> Add a toggle for auto indentation

- dockerfile-mode.el
`docker build` supports two handy switches:
- `--force-rm` to remove build containers on build error.
- `--pull` to force checking of base image and pulling it if more recent.
Two new `defcustoms` have been defined, respectively:
- `dockerfile-build-force-rm`
- `dockerfile-build-pull`
Both default to `nil` to keep current behavior.
> Add --pull and --force-rm switches toggling defcustoms.

- dockerfile-mode.el
some terminals won't handle ANSI escape codes very well (compilation mode in my Emacs won't, even after setting some configurations). By default, docker build uses "auto" for this flag but it is desirable in several cases to use "plain" as a value here.
> feat(build): add option to specify --progress flag

- dockerfile-mode.el
"Containerfile" is a renaming of "Dockerfile" used by Buildah, Podman,
etc. The same syntax is used.
https://www.mankier.com/5/Containerfile
> Recognize Containerfile

- README.md
That line is no longer necessary because `auto-mode-alist` is set by below part.
https://github.com/spotify/dockerfile-mode/blob/11c43de04b128b7638cd98a1e80be2b661c18fbb/dockerfile-mode.el#L264-L269
> Remove unnecessary configuration

- dockerfile-mode.el
The older code has been always deleting the whitespace, even if indentation is already as expected. Fix that by replacing `indent-to` with `indent-line-to` which avoids modifying the line if there's nothing to modify.
As a bonus, this simplifies the code.
> Do not modify indentation if there's nothing to modify

- dockerfile-mode.el
In Emacs 29.1 the `point-at-bol` and `point-at-eol` functions are obsolete. This removes the following warnings when compiling the file:
In dockerfile-indent-line-function:
dockerfile-mode.el:159:41: Warning: ‘point-at-bol’ is an obsolete function (as
of 29.1); use ‘line-beginning-position’ or ‘pos-bol’ instead.
dockerfile-mode.el:163:37: Warning: ‘point-at-eol’ is an obsolete function (as
of 29.1); use ‘line-end-position’ or ‘pos-eol’ instead.
dockerfile-mode.el:164:32: Warning: ‘point-at-eol’ is an obsolete function (as
of 29.1); use ‘line-end-position’ or ‘pos-eol’ instead.
dockerfile-mode.el:166:27: Warning: ‘point-at-bol’ is an obsolete function (as
of 29.1); use ‘line-beginning-position’ or ‘pos-bol’ instead.
It is safe to use these new functions as they were introduced as of Emacs …
> Remove obsolete function calls

- dockerfile-mode.el
After afcd418, dockerfile-mode fails to load with:
```
File mode specification error: (file-missing Cannot open load file No such file or directory s)
```
This is because dockerfile-mode depends now on the function
`s-replace`, which is provided by the `s` package. This commit adds
`s` to the list of dependencies of dockerfile-mode.
Fixes #83.
> Add s to Package-Requires list

- dockerfile-mode.el
Fixes a warning:
dockerfile-mode.el:121:12: Warning: ‘font-lock-keyword-face’ is an obsolete variable (as of 31.1); use the quoted symbol instead: 'font-lock-keyword-face
> Make sure to quote font-lock-keyword-face
